// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9a4OtcP7ay6A3Pqprs_ZCDzqb4aTau1s',
    appId: '1:506391506267:web:517e627482c4b888a57e7e',
    messagingSenderId: '506391506267',
    projectId: 'visoattend',
    authDomain: 'visoattend.firebaseapp.com',
    storageBucket: 'visoattend.appspot.com',
    measurementId: 'G-WBXDR9D56H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu2oP7SVmY66KeQY5KXfizwSxMthCR4-Q',
    appId: '1:506391506267:android:09b3b75d48d0301ca57e7e',
    messagingSenderId: '506391506267',
    projectId: 'visoattend',
    storageBucket: 'visoattend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGCmdCDHh1qBwV-218vgboo7f1i-CS5Z4',
    appId: '1:506391506267:ios:b6ba6838d423be3da57e7e',
    messagingSenderId: '506391506267',
    projectId: 'visoattend',
    storageBucket: 'visoattend.appspot.com',
    iosClientId: '506391506267-rk439losivapkptdq025kfpj2fmrqoc3.apps.googleusercontent.com',
    iosBundleId: 'com.example.visoattend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGCmdCDHh1qBwV-218vgboo7f1i-CS5Z4',
    appId: '1:506391506267:ios:a2a8e1c871149311a57e7e',
    messagingSenderId: '506391506267',
    projectId: 'visoattend',
    storageBucket: 'visoattend.appspot.com',
    iosClientId: '506391506267-a6ek1evt0i3uskee6ap2coin57vleu5p.apps.googleusercontent.com',
    iosBundleId: 'com.example.visoattend.RunnerTests',
  );
}
